### ISSUE TITLE
Composition capability of SDXL 

### ISSUE THREAD

**Issue by junwenxiong** [mlpc-ucsd/TokenCompose#3]
I was surprised to find that the SDXL model addresses the problem of multi-category object composition.
![image](https://github.com/mlpc-ucsd/TokenCompose/assets/35716657/2f242bb5-6d3c-4643-acac-862cbe9c9a13)
![image](https://github.com/mlpc-ucsd/TokenCompose/assets/35716657/38b4eb99-8b2f-4f86-b13f-afb08683a52d)

**Comment by zwcolin** [comment]
Hi Junwen,

Thanks for your comments! From both a research or practical perspective, we wouldn't say a problem as being "addressed" simply based on some examples. Metrics have its quantitative measurements -- to truly say that a model addresses multi-category object composition, likely you would need a model so powerful that you can literally give it as many categories of objects as possible and it will generate all these categories of objects for all its generated images. For example, given enough compute, try SDXL with say, MultiGen-10 or MultiGen-15, and the results will very likely be imperfect.

For example, SDXL image generations of the prompt, "a photo of a clock, an elephant, a toilet, a cat, a suitcase, and a helicopter, an umbrella, a tea cup, a dining table, and an astronaut on a horse" will almost always miss certain categories of instances:

![image](https://github.com/mlpc-ucsd/TokenCompose/assets/59942464/c1fff7e1-7743-4a0e-afdb-0a82d5b4438d)
![image](https://github.com/mlpc-ucsd/TokenCompose/assets/59942464/8b6db236-44b2-46f2-84e8-ade77266741e)
![image](https://github.com/mlpc-ucsd/TokenCompose/assets/59942464/616e6c9a-d0c4-4c2b-92da-0610be1bdb9a)
![image](https://github.com/mlpc-ucsd/TokenCompose/assets/59942464/c4a651f4-d92d-48df-9957-25256852625e)

For stronger models such as SDXL, you'd likely need to try prompts that involve more categories of instances to see that it is still an issue (and also categories of instances where they do not commonly appear together naturally).

As a research project, we are implementing our approach on SD 1.4 and SD 2.1 because the compute need for training SDXL is beyond our capacity, but we hope our approach can improve any existing model on multi-category instance composition (as we've seen significant improvements on both SD 1.4 and SD 2.1).

Hope this addresses your concerns, and let us know if you have any follow-up questions!

Best,
Colin
