### ISSUE TITLE
Could you please provide the training log?

### ISSUE THREAD

**Issue by felixfuu** [mlpc-ucsd/TokenCompose#7]

**Comment by zwcolin** [comment]
Hi Felix,

Please find the [report](https://api.wandb.ai/links/zwcolin/cqmhrgp6) for our training log. We provide loss curves for [this](https://huggingface.co/mlpc-lab/TokenCompose_SD21_A) model.

**Comment by felixfuu** [comment]
> Hi Felix,
> 
> Please find the [report](https://api.wandb.ai/links/zwcolin/cqmhrgp6) for our training log. We provide loss curves for [this](https://huggingface.co/mlpc-lab/TokenCompose_SD21_A) model.

@zwcolin 
[report](https://wandb.ai/zwcolin/TokenCompose/reports/Loss-Log--Vmlldzo3MzM2NDA4) is a private report and cannot be viewed

`This set of panels contains runs from a private project, which cannot be shown in this report`

**Comment by felixfuu** [comment]
![20240329121023](https://github.com/mlpc-ucsd/TokenCompose/assets/30679630/56594fcd-1d00-4ef0-8604-dccf1ed4a21f)

**Comment by zwcolin** [comment]
[Loss Log _ TokenCompose – Weights & Biases.pdf](https://github.com/mlpc-ucsd/TokenCompose/files/14856106/Loss.Log._.TokenCompose.Weights.Biases.pdf)

Due to administrative settings it seems that there are some glitches in viewing the log. I attached the downloaded report from the report page with all the curves (note that I set an EMA smoothing with a factor of 0.5 for better illustration purposes).
